export enum FlowGramNode {
  Root = 'root',
  Start = 'start',
  End = 'end',
  LLM = 'llm',
  Code = 'code',
  Condition = 'condition',
  Loop = 'loop',
  Comment = 'comment',
  Group = 'group',
  BlockStart = 'block-start',
  BlockEnd = 'block-end',
  HTTP = 'http',
  Break = 'break',
  Continue = 'continue',
  Docker = 'Docker',
  GPP = 'GPP',
  MPI = 'MPI',
  Diskin = 'Diskin',
  Diskout = 'Diskout',
  LoopInfinite = 'loop-infinite',
  LoopCount = 'loop-count',
  Module = 'module',
  SetVariable = 'setVariable',
}